tests: Relax unnecessarily-strict constraint
Debian's parted package carries a patch to apply alignment constraints
to new partitions created on fresh disks.  This caused
`tests.test__ped_partition.PartitionMSDOSTypeIDTestCase.runTest` to fail
as follows:

  _ped.PartitionException: Unable to satisfy all constraints on the partition.

While I realize that a Debian patch isn't strictly upstream's problem,
in this case the optimal alignment constraint doesn't seem to have
anything to do with what's actually being tested, so relax it to a
minimal alignment constraint.